config/routes.rb
Rails.application.routes.draw do

  root "pages#index"

  devise_for :users,
             :skip         => [:sessions],
             :controllers  => { :omniauth_callbacks => "users/omniauth_callbacks" }

  as :user do
    match "login",   :to => "sessions#new",      :via => :get,     :as => :new_user_session
    match "logout",  :to => "sessions#destroy",  :via => :delete,  :as => :destroy_user_session
  end

  resources :users, :only => [:show, :edit, :update] do
    post :edit_job,     :on => :member, :as => :edit_job
    post :edit_name,    :on => :member, :as => :edit_name
    post :update_job,   :on => :member, :as => :update_job
    post :update_name,  :on => :member, :as => :update_name
  end

  resources :recipes

  get :paginate, :as => :paginate, :to => "pages#paginate"
  get :search,   :as => :search,   :to => "pages#search"

  resources :votes, :only => [] do
    post :toggle,   :on => :member, :as => :toggle
    post :create,   :on => :member, :as => :create
    post :destroy,  :on => :member, :as => :destroy
  end

  resources :comments, :only => [:create, :update, :destroy, :edit]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe

  validates :text,    :presence => true
  validates :user,    :presence => true
  validates :recipe,  :presence => true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  def create
    @recipe = Recipe.find(params[:recipe])
    @comment = current_user.comments.new(:recipe => @recipe, :text => params[:comment])

    respond_to do |format|
      if @comment.save
        format.js { render layout: false, content_type: 'text/javascript'}
      else
        format.json { render :json => @comment.errors, :status => 500}
      end
    end
  end

  def edit
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.js { render layout: false, content_type: 'text/javascript'}
    end
  end

  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update(:text => params[:comment])
        format.js { render layout: false, content_type: 'text/javascript'}
      else
        format.json { render :json => @comment.errors, :status => 500}
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.js { render layout: false, content_type: 'text/javascript'}
    end
  end

end

app/views/comments/_comment.haml
%div{:id => "cpanel-#{comment.id}"}
  .panel.panel-default
    .panel-heading
      %strong Posted by:
      = comment.user.name
      - if current_user == comment.user
        = link_to "Edit", edit_comment_path(comment), :remote => true
        = link_to "Delete", comment, :remote => true, :method => :delete, :data => { :confirm => "Are you sure you want to delete this comment?"}
      .pull-right
        %strong
          = comment.created_at.strftime("%c")
    .panel-body
      %div{:id => "comment-#{comment.id}"}
        = comment.text

app/views/comments/_comment_form.haml
= form_tag comments_path, :remote => true do
  .form-group
    = text_area_tag :comment,"", :placeholder => "Add a comment", :class => "form-control", :id => "comment", :style => "margin-top: 20px;"
    = hidden_field_tag :recipe, @recipe.id
    = submit_tag "Post", :class => "form-control btn btn-primary", :style => "margin-top: 20px;"

app/views/comments/_comments.haml
= render @recipe.comments
= render "comment_form"

app/views/comments/_edit_comment.haml
= form_tag @comment, :remote => true, :id => "comment_form", :method => :PATCH do
  .form-group
    = text_area_tag :comment, @comment.text, :placeholder => "Add a comment", :class => "form-control", :id => "comment", :style => "margin-top: 20px;", :required => true
    = submit_tag "Submit", :class => "form-control btn btn-primary", :style => "margin-top: 20px;", :id => "comment_submit"

app/views/comments/create.js.erb
$(".comments").html("<%= j render(:partial => 'comments') %>")

app/views/comments/destroy.js.erb
$("#cpanel-<%= @comment.id %>").remove()

app/views/comments/edit.js.erb
$("#comment-<%= @comment.id %>").html("<%= j render('edit_comment') %>");

app/views/comments/update.js.erb
$("#comment-<%= @comment.id %>").html("<%= @comment.text %>");