config/routes.rb
Rails.application.routes.draw do

  root "pages#index"

  devise_for :users,
             :skip         => [:sessions],
             :controllers  => { :omniauth_callbacks => "users/omniauth_callbacks" }

  as :user do
    match "login",   :to => "sessions#new",      :via => :get,     :as => :new_user_session
    match "logout",  :to => "sessions#destroy",  :via => :delete,  :as => :destroy_user_session
  end

  resources :users, :only => [:show, :edit, :update] do
    post :edit_job,     :on => :member, :as => :edit_job
    post :edit_name,    :on => :member, :as => :edit_name
    post :update_job,   :on => :member, :as => :update_job
    post :update_name,  :on => :member, :as => :update_name
  end

  resources :recipes

  get :paginate, :as => :paginate, :to => "pages#paginate"
  get :search,   :as => :search,   :to => "pages#search"

  resources :votes, :only => [] do
    post :toggle,   :on => :member, :as => :toggle
    post :create,   :on => :member, :as => :create
    post :destroy,  :on => :member, :as => :destroy
  end

  resources :comments, :only => [:create, :update, :destroy, :edit]

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  belongs_to :user
  has_many   :votes,    :dependent => :destroy
  has_many   :comments, :dependent => :destroy

  validates :title,    :presence => true, :length  => { :maximum => 255 }
  validates :tagline,  :presence => true, :length  => { :maximum => 255 }
  validates :link,     :presence => true
  validates :user,     :presence => true

  validate  :user_under_limit?, :on => :create

  validates_format_of :link,  :with => /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\Z/i,   :message => "Please use a valid url"
  validates_format_of :image, :with => /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\Z/i,  :message => "Please use a valid url", :allow_nil => true

  def self.ordered
    order("votes_count DESC")
  end

  def self.filter_by_date(start_date, end_date)
    where(:created_at => start_date.to_time..end_date.to_time)
  end

  def user_under_limit?
    if Recipe.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day, user: user).count > 1
      errors.add(:user, "You can't post more than two times a day")
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]
  before_action :check_user, :only => [:edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render :edit
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to root_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :tagline, :link, :image, :user)
  end

  def check_user
    @recipe = Recipe.find(params[:id])

    if current_user != @recipe.user
      redirect_to root_path, :notice => "You are not authorized to complete this action"
    end
  end
end

app/views/recipes/_form.haml
- if @recipe.errors.messages[:user]
  %p.notice.alert-dismissible.alert-warning{:style => "padding: 10px"}
    = @recipe.errors.messages[:user].first

= form_for @recipe, :html => { :class => "form-horizontal" } do |f|
  %fieldset
    .form-group.recipe-form
      = f.label :title, :class => "control-label"
      = f.text_field :title, :class => "form-control"
      = f.error_message_on :title, :class => "form-control"
    .form-group.recipe-form
      = f.label :tagline, :class => "control-label"
      = f.text_field :tagline, :class => "form-control"
      = f.error_message_on :tagline, :class => "form-control"
    .form-group.recipe-form
      = f.label :link, :class => "control-label"
      = f.text_field :link, :class => "form-control"
      = f.error_message_on :link, :class => "form-control"
    .form-group.recipe-form
      = f.label :image, :class => "control-label"
      = f.text_field :image, :class => "form-control"
      = f.error_message_on :image, :class => "form-control"
    .form-group.recipe-form
      = f.submit "Submit", :class => "btn btn-primary"

app/views/recipes/_recipe.haml
.panel.panel-default
  .panel-heading
    = render "recipes/recipe_heading", :recipe => recipe
  .panel-body
    = render "recipes/recipe_body", :recipe => recipe

app/views/recipes/_recipe_body.haml
= recipe.tagline
%div.swag.pull-right{:style => "margin-left: 10px;"}
  - if current_user
    - if current_user.voted?(recipe)
      = link_to "Unvote", toggle_vote_path(:id => recipe.id, :voted => true ), :remote => true, :method => :post, :id => "vote-#{recipe.id}", :class => "btn btn-success col-md-12 vote"
    - else
      = link_to "&nbsp;&nbsp; Vote &nbsp;&nbsp;".html_safe, toggle_vote_path(:id => recipe.id, :voted => false ), :remote => true, :method => :post, :id => "vote-#{recipe.id}", :class => "btn btn-primary col-md-12 vote"
  - else
    = link_to "Vote", new_user_session_path, :class => "btn btn-primary col-md-12 "

= link_to "Try it out", recipe.link, :class => "btn btn-info pull-right"
= link_to "Comments", recipe, :class => "btn btn-warning pull-right", :style => "margin-right: 10px;"

- if current_user == recipe.user
  = link_to "Delete", recipe, :class => "btn btn-danger pull-right", :style => "margin-right: 10px;", :method => :delete, :data => { :confirm => "Are you sure you want to delete this recipe?"}
  = link_to "Edit", edit_recipe_path(recipe), :class => "btn btn-default pull-right", :style => "margin-right: 10px;"

= link_to "Submitter", recipe.user, :class => "btn btn-user pull-right", :style => "margin-right: 10px;" if @recipe

app/views/recipes/_recipe_heading.haml
%strong
  = recipe.title
%p.pull-right
  %strong
    .votes.pull-right{:id => "#{recipe.id}"}
      = recipe.votes.count
    .pull-right{:style => "margin-right: 5px"}
      Votes:

app/views/recipes/edit.haml
%h1 Edit your recipe
= render "form"

app/views/recipes/new.haml
.container
  .col-md-9.col-md-offset-1
    .page-header
      %h1 Post a new recipe
    = render "form"

app/views/recipes/show.haml
.recipes-row
  = render @recipe

.page-header
  %h3 Comments

.comments
  = render @recipe.comments
  = render "comments/comment_form" if current_user