config/routes.rb
Rails.application.routes.draw do

  root "pages#index"

  devise_for :users,
             :skip         => [:sessions],
             :controllers  => { :omniauth_callbacks => "users/omniauth_callbacks" }

  as :user do
    match "login",   :to => "sessions#new",      :via => :get,     :as => :new_user_session
    match "logout",  :to => "sessions#destroy",  :via => :delete,  :as => :destroy_user_session
  end

  resources :users, :only => [:show, :edit, :update] do
    post :edit_job,     :on => :member, :as => :edit_job
    post :edit_name,    :on => :member, :as => :edit_name
    post :update_job,   :on => :member, :as => :update_job
    post :update_name,  :on => :member, :as => :update_name
  end

  resources :recipes

  get :paginate, :as => :paginate, :to => "pages#paginate"
  get :search,   :as => :search,   :to => "pages#search"

  resources :votes, :only => [] do
    post :toggle,   :on => :member, :as => :toggle
    post :create,   :on => :member, :as => :create
    post :destroy,  :on => :member, :as => :destroy
  end

  resources :comments, :only => [:create, :update, :destroy, :edit]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :recipes
  has_many :votes
  has_many :comments

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name      = auth.info.name
      user.email     = auth.info.email
      user.image     = auth.info.image + "?type=large"
      user.password  = Devise.friendly_token[0,20]
    end
  end

  def submitted
    Recipe.where(:user => self)
  end

  def voted
    recipes = []

    votes = Vote.where(:user => self)
    votes.each do |vote|
      recipes.push(vote.recipe)
    end
    recipes
  end

  def voted?(recipe)
    recipe.votes.each do |vote|
      if vote.user = self
        return true
      end
    end
    false
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, :except => [:show]

  def show
    @user = User.find(params[:id])
  end

  def edit_job
    @user = User.find(params[:id])

    respond_to do |format|
      format.js { render layout: false, content_type: 'text/javascript'}
    end
  end

  def update_job
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update(:job => params[:job])
        format.js { render layout: false, content_type: 'text/javascript'}
      else
        format.json { render :json => @user.errors, :status => 500}
      end
    end
  end

  def edit_name
    @user = User.find(params[:id])

    respond_to do |format|
      format.js { render layout: false, content_type: 'text/javascript'}
    end
  end

  def update_name
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update(:name => params[:name])
        format.js { render layout: false, content_type: 'text/javascript'}
      else
        format.json { render :json => @user.errors, :status => 500}
      end
    end
  end

end

app/views/users/_jobform.haml
= form_tag update_job_user_path(current_user), :remote => true, :id => "job_form", :method => :POST, :class => "form-group col-md-4 col-md-offset-4" do
  .input-group{:style => "padding-top:20px"}
    = text_field_tag :job, @user.job, :placeholder => "Add a job title...", :class => "form-control", :id => "add_job", :required => true
    .input-group-btn
      = submit_tag "Submit", :class => "btn btn-primary"

app/views/users/_nameform.haml
= form_tag update_name_user_path(current_user), :remote => true, :id => "name_form", :method => :POST, :class => "form-group col-md-9 col-md-offset-2 name-form" do
  .input-group{:style => "padding-top:20px"}
    = text_field_tag :name, @user.name, :class => "form-control", :id => "edit_name", :required => true
    .input-group-btn
      = submit_tag "Submit", :class => "btn btn-primary"

app/views/users/edit_job.js.erb
$(".job").html("<%= j render 'jobform' %></div><br><br><br><br><br>");

app/views/users/edit_name.js.erb
$(".name").html("<%= j render 'nameform' %></div>");

app/views/users/show.haml
.row
  .col-md-6.col-md-offset-5
    = image_tag @user.image, :width => 150, :height => 150, :style => "border-radius: 50%;"

.name{:style => "padding-top:20px"}
  = @user.name
  - if current_user == @user
    = link_to 'Edit', edit_name_user_path(@user), :id => 'edit_name', :style => "font-size: 16px", :remote => true, :method => :POST
%br
.job{:style => "margin-bottom: 20px;"}
  - if @user.job?
    .center-text
      = @user.job
      - if current_user == @user
        = link_to 'Edit', edit_job_user_path(@user), :id => 'edit_job', :style => 'font-size: 12px', :remote => true, :method => :POST
  - elsif @user == current_user
    = render "jobform"
  - else
    Foodhunt User
%br

.recipes-row
  .page-header
    %h3 Submitted
  = render @user.submitted
  .page-header
    %h3 Voted
  = render @user.voted

app/views/users/update_job.js.erb
$(".job").html("<div class='center-text'><%= @user.job %> <%= j link_to 'Edit', edit_job_user_path(@user), :id => 'edit_job', :style => 'font-size: 12px', :remote => true, :method => :POST %></div>");

app/views/users/update_name.js.erb
$(".name").html("<%= @user.name %> <%= j link_to 'Edit', edit_name_user_path(@user), :id => 'edit_name', :style => 'font-size: 16px', :remote => true, :method => :POST%>");